export { default as NavBar } from './NavBar'
export { default as Carousel } from './Carousel'
export { default as UpcomingTournaments } from './Tournaments/upcoming'
export { default as InprogressTournaments } from './Tournaments/inprogress'
export { default as CreateYourOwnTournament } from './Tournaments/createyourown'
export { default as CompletedTournaments } from './Tournaments/completed'
export { default as Discord } from './Tournaments/discord'
export { default as Features } from './Features'